services:
  - type: web
    name: clinic-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://frontend-rho-bice-58.vercel.app
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: jwtSecret
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_CHAT_MODEL
        sync: false
      - key: GROQ_CLASSIFIER_MODEL
        sync: false
